#+title: Cookbook Ru
#+auto_tangle: t

Таблица соотношения объема к весу:
Стакан - 250мл
* Таблица соответствий

#+name: p2p
| Продукт            | грамм/стакан | грамм/ст. ложку |
|--------------------+--------------+-----------------|
| Вода               |          250 |              15 |
| Гречка             |          210 |              27 |
| Дрожжи             |          100 |              10 |
| Кефир              |          160 |              18 |
| Масло растительное |          140 |              20 |
| Мед                |          320 |              35 |
| Молоко             |          250 |              15 |
| Мука пшеничная     |          160 |              45 |
| Рис                |          240 |              27 |
| Сливочное масло    |          320 |              22 |
| Соль               |          325 |              30 |

* Computation code
:PROPERTIES:
:header-args: :tangle cook-fun-ru.el :results silent
:END:

*Turn on closures*
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

#+name: how-many-cups
#+begin_src emacs-lisp :var p2p=p2p
(require 'dash)

(defvar insert-instantly t
  "Write result instanly in the end of the line.")

(defun how-many-ru (&optional product grams)
  "Look for in table product and return count of cups or spoons."
  (interactive)
  (setq product (or product
                    (let* ((choices (-map 'car p2p))
                           (selection (completing-read "Выберете продукт: " choices)))
                      selection)))
  (setq grams (or grams
                  (when (not (string-empty-p (current-word))) (ignore-errors (string-to-number (current-word))))
                  (read-number "Сколько грамм? ")))
  (let ((product-proportion (-find (lambda (coll) (string= product (car coll))) p2p)))
    (if product-proportion
        (let* ((cups? (>= grams 100))
               (res (/ (* grams 1.0) (nth (if cups? 1 2) product-proportion)))
               (measure-thing (if cups? "стакана" "ложек")))
          (message (format "Для %d гр. нужно %.2f %s" grams res measure-thing ))
          (when insert-instantly
            (save-excursion
            (end-of-line)
            (insert (format " (%.2f %s)" res measure-thing)))))
      (concat "Не получилось найти продукт по имени: " product))))
#+end_src

* Обновить таблицу соответсвий
#+begin_src emacs-lisp :results silent
(with-temp-buffer
  (insert-file-contents "./cook-fun-ru.el")
  (eval-buffer)
  (message "Таблица соответсвий обновлена!"))
#+end_src

* Пельмени

_Тесто:_
1. Мука пшеничная - 500 г + для работы с тестом (3.12 стакана)
2. Вода горячая (70-75 градусов) - 250 мл (1.00 стакана)
3. Яйцо (небольшое) - 1 шт.
4. Соль - 1 ч. ложка без горки
5. Масло растительное без запаха - 25 мл (1.25 ложки)

_Для начинки:_
1. Мясо (говядина и свинина) - 550 г
2. Лук репчатый - 200 г
3. Сало (по желанию, если мясо постное) - 30 г
4. Вода - 70-80 г (по консистенции фарша)
5. Соль - 1 ч. ложка без горки
6. Перец чёрный молотый - по вкусу

_Для варки:_
1. Лист лавровый - по вкусу
2. Соль - по вкусу
3. Перец чёрный горошком - по вкусу
4. Лук репчатый - 1/4 шт.

_Для подачи:_
Масло сливочное - по вкусу

- Note taken on [2024-10-20 Sun 20:19] \\
  Получилось многовато теста, так что возможно стоит брать муки грамм 400-420.
* Пироги

_Тесто:_
1. теплая вода – 100 мл;
2. теплое молоко – 100 мл;
3. мука – 450 г (2.81 стакана)
4. яйца – 2 шт.;
5. сухие быстродействующие дрожжи – 7 г (0.70 ложки)
6. сахар – 2 ст. л. в тесто + 0,5 стакана для начинки;
7. масло сливочное – 70 г. (3.18 ложки) в тесто + 30 г (1.36 ложки) для начинки;
8. соль – 2 щепотки.

_Что делать?_
Молоко слегка погреть.
Замесить тесто без добавления масла, как тестно будет готово, вмесить масло в тесто, лучше конечно немного его погреть.
Как тесто поднимется надо разделить его на колобки и 10 минут дать отдохнуть. После отдыха колобки надо слегка раскатать и выложить начинку внутрь, обычно начинка хватает одной столовой ложки, слепить края начиная с центра и перевернуть пирожок швом вниз. Дать постоять 30-40 минут, после чего разогреть духовку до 200-220 градусов и выпикать 15-18 минут.

* Манты

_Тесто:_
1. 1000 г муки (6.25 стакана)
2. 350-400 мл.л воды (в воду можно добавить немного масла) (1.40 стакана)
3. 1 куриное яйцо

//TODO граммовки
_Для начинки:_
1. Лук
2. Картофель
3. Мясо
4. Соль
5. Перец

_Что делать?_
После замеса можно убрать тесто в морозилник, что бы оно еще немного дало влаги с лучше смешалось. Пока можно заняться начинкой, лук, картофель, мясо, посолить, поперчить и можно добавить паприку для цвета и вкуса. Перемешать.
* Пицца
Опару настаивать 1 час при комнатной температуре или 24 часа в холодильнике.

_Рецепт опары:_
- 300 мл Вода (1.20 стакана)
- 300 гр. Мука (1.88 стакана)
- 5 гр Сухие дрожжи (0.50 ложек)
- 5 гр Мед (0.14 ложек)

_Тесто:_
 - Опара
 - 700 мл Воды (2.80 стакана)
 - 40 гр. Морская соль (1.33 ложек)
 - 1250 гр. Мука (7.81 стакана)

После замешивания тесто станет липким, его нужно просто оставить на 15 минут.
Следующим шагом формируем из теста большой шар и оставляем его на 30 минут. После можно разделить на небольшие шарики и оставить еще на 2 часа, после чего нужно выпекать.
* Куриная грудка с сыром запеченая в духовке

_Рецепт:_
1. Сначала маринуем курицу
   Перемешать и оставить на минут 30
   Маринад:
   - итальянские приправы
   - чеснок (весь)
   - лимонный сок
   - свежий тимьян или сушеный (можно размарин)
   - черный перец
   - соль
   - оливковое масло
   - цедра лимона
2. Разогреваем скорворду и слегка обжариваем грудки
3. Делаем продольные разрезы по курице и начиняем грудку дольками сыра
4. Укладываем грудки в форму для запикания
5. Маринад так же можно использовать для помидор, слегка повалять там томаты и отправить в ту же форму для запикания
6. Запекать в духовке разогретой до 180 градусов на 10 минут
