#+title: Cookbook Ru
#+auto_tangle: t

Таблица соотношения объема к весу:
Стакан - 250мл
* Таблица соответствий

#+name: p2p
| Продукт            | грамм/стакан | грамм/ст. ложку |
|--------------------+--------------+-----------------|
| Вода               |          250 |              15 |
| Гречка             |          210 |              27 |
| Дрожжи             |          100 |              10 |
| Кефир              |          160 |              18 |
| Масло растительное |          140 |              20 |
| Мед                |          320 |              35 |
| Молоко             |          250 |              15 |
| Мука пшеничная     |          160 |              45 |
| Рис                |          240 |              27 |
| Сливочное масло    |          320 |              22 |
| Соль               |          325 |              30 |

* Computation code
:PROPERTIES:
:header-args: :tangle cook-fun-ru.el :results silent
:END:

*Turn on closures*
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

#+name: how-many-cups
#+begin_src emacs-lisp :var p2p=p2p
(require 'dash)

(defvar insert-instantly t
  "Write result instanly in the end of the line.")

(defun how-many-cups-ru (&optional product grams)
  "Look for in table product and return count of cups."
  (interactive)
  (setq product (or product
                    (let* ((choices (-map 'car p2p))
                           (selection (completing-read "Выберете продукт: " choices)))
                      selection)))
  (setq grams (or grams
                  (ignore-errors (string-to-number (current-word)))
                  (read-number "Сколько грамм? ")))
  (let ((product-proportion (-find (lambda (coll) (string= product (car coll))) p2p)))
    (if product-proportion
        (let ((res (/ (* grams 1.0) (nth 1 product-proportion))))
          (message (format "Для %d гр. нужно %.2f стакана" grams res))
          (save-excursion
            (end-of-line)
            (insert (format " (%.2f стакана)" res))))
      (concat "Не получилось найти продукт по имени: " product))))

(defun how-many-spoons-ru (&optional product grams)
  "Look for in table product and return count of spoons."
  (interactive)
  (setq product (or product
                    (let* ((choices (-map 'car p2p))
                           (selection (completing-read "Выберете продукт: " choices)))
                      selection)))
  (setq grams (or grams
                  (ignore-errors (string-to-number (current-word)))
                  (read-number "Сколько грамм? ")))
  (let ((product-proportion (-find (lambda (coll) (string= product (car coll))) p2p)))
    (if product-proportion
        (let ((res (/ (* grams 1.0) (nth 2 product-proportion))))
          (message (format "Для %d гр. нужно %.2f столовых ложек" grams res))
          (save-excursion
            (end-of-line)
            (insert (format " (%.2f ложки)" res))))
      (concat "Не получилось найти продукт по имени: " product))))
#+end_src

* Обновить таблицу соответсвий
#+begin_src emacs-lisp :results silent
(with-temp-buffer
  (insert-file-contents "./cook-fun-ru.el")
  (eval-buffer)
  (message "Таблица соответсвий обновлена!"))
#+end_src

* Пельмени

_Тесто:_
1. Мука пшеничная - 500 г + для работы с тестом или 3 стакана
2. Вода горячая (70-75 градусов) - 250 мл
3. Яйцо (небольшое) - 1 шт.
4. Соль - 1 ч. ложка без горки
5. Масло растительное без запаха - 25 мл

_Для начинки:_
1. Мясо (говядина и свинина) - 550 г
2. Лук репчатый - 200 г
3. Сало (по желанию, если мясо постное) - 30 г
4. Вода - 70-80 г (по консистенции фарша)
5. Соль - 1 ч. ложка без горки
6. Перец чёрный молотый - по вкусу

_Для варки:_
1. Лист лавровый - по вкусу
2. Соль - по вкусу
3. Перец чёрный горошком - по вкусу
4. Лук репчатый - 1/4 шт.

_Для подачи:_
Масло сливочное - по вкусу

- Note taken on [2024-10-20 Sun 20:19] \\
  Получилось многовато теста, так что возможно стоит брать муки грамм 400-420.
* Пироги

_Тесто:_
1. теплая вода – 100 мл;
2. теплое молоко – 100 мл;
3. мука – 450 г или почти 3 стакана (не досыпая последний);
4. яйца – 2 шт.;
5. сухие быстродействующие дрожжи – 7 г, 3/4 столовой ложки;
6. сахар – 2 ст. л. в тесто + 0,5 стакана для начинки;
7. масло сливочное – 70 г. (3 ст. ложки с горкой) в тесто + 30 г (1.5 ложки) для начинки;
8. соль – 2 щепотки.

_Что делать?_
Молоко слегка погреть.
Замесить тесто без добавления масла, как тестно будет готово, вмесить масло в тесто, лучше конечно немного его погреть.
Как тесто поднимется надо разделить его на колобки и 10 минут дать отдохнуть. После отдыха колобки надо слегка раскатать и выложить начинку внутрь, обычно начинка хватает одной столовой ложки, слепить края начиная с центра и перевернуть пирожок швом вниз. Дать постоять 30-40 минут, после чего разогреть духовку до 200-220 градусов и выпикать 15-18 минут.

* Манты

_Тесто:_
1. 1 кг муки или 6.25 стакана
2. 350-400 мл.л воды (в воду можно добавить немного масла) или 1.6 стакана
3. 1 куриное яйцо

//TODO граммовки
_Для начинки:_
1. Лук
2. Картофель
3. Мясо
4. Соль
5. Перец

_Что делать?_
После замеса можно убрать тесто в морозилник, что бы оно еще немного дало влаги с лучше смешалось. Пока можно заняться начинкой, лук, картофель, мясо, посолить, поперчить и можно добавить паприку для цвета и вкуса. Перемешать.
* Пицца
Опару настаивать 1 час при комнатной температуре или 24 часа в холодильнике.

_Рецепт опары:_
- 300 мл Вода (1.2 стакана)
- 300 гр. Мука (1.9 стакана)
- 5 гр Сухие дрожжи (пол столовой ложки)
- 5 гр Мед (меньше половину столовой ложки)

_Тесто:_
 - Опара (вся)
 - 700 мл Воды (2.80 стакана)
 - 40 гр. Морская соль (1.33 ложки)
 - 1250 гр. Мука (7.81 стакана)

После замешивания тесто станет липким, его нужно просто оставить на 15 минут.
Следующим шагом формируем из теста большой шар и оставляем его на 30 минут. После можно разделить на небольшие шарики и оставить еще на 2 часа, после чего нужно выпекать.
