#+title: Readme

* Повареная книга программиста
В файле [[./Cookbook.org][Cookbook]] лежат рецепты которые я готовлю и которые не хочу потерять и которые мне бы хотелсь как то корректировать. А что может быть лучше чем репортить о багах в рецепте через issue и делать hot fixes на рецепты пирожков. Ни одна повареная книга не позволит вам реализовать такой контроль версий как *git*.

Из автоматизаций:
В книге используется таблица соответствий которая помогает вычислять кол-во мер которые есть почти на каждой кухне, стаканы и ложки. Особенно полезно когда нет кухонных весов.

Если кого то угораздит этим попользоваться нужно сделать следующее:
1. Скачиваете проект ~git clone https://github.com/Prikaz98/cookbook.git~
2. Заходите в [[./Cookbook.org][Cookbook]]
3. Находите раздел "Обновить таблицу соответсвий"
4. Встаете на src_block и вызываете функцию ~org-babel-execute-src-block~
   Она прочитает файл с полезными функциями и таблицей соответсвий.
5. После чего можете пользоваться дописывая свои рецепты и т.д.
   Тоже самое надо делать каждый раз когда вы меняете таблицу для актуализации данных.
